# Generated by Django 4.2.1 on 2023-06-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_code', models.CharField(db_column='Group_Code', max_length=20, primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='Group_Name', max_length=10)),
                ('creator_id', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='Creator_ID', max_length=100)),
            ],
            options={
                'db_table': 'group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=100)),
                ('name', models.CharField(db_column='Name', max_length=10)),
                ('join_date', models.DateField(db_column='Join_Date')),
                ('is_active', models.IntegerField(db_column='is_Active')),
                ('time_table', models.BinaryField(blank=True, db_column='Time_Table', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_id', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='Time_ID', max_length=15, null=True)),
                ('day', models.IntegerField(db_column='Day', null=True)),
                ('time', models.IntegerField(db_column='Time', null=True)),
                ('preference', models.IntegerField(blank=True, db_column='Preference', null=True)),
                ('email', models.OneToOneField(db_column='Email', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'time',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupTimetable',
            fields=[
                ('timetable_id', models.IntegerField(db_column='Timetable_ID', primary_key=True, serialize=False)),
                ('start_time', models.DateField(db_column='Start_Time')),
                ('end_time', models.DateField(db_column='End_Time')),
                ('group_code', models.ForeignKey(db_column='Group_Code', on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
            options={
                'db_table': 'group_timetable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('schedule_id', models.IntegerField(db_column='Schedule_ID', primary_key=True, serialize=False)),
                ('schedule_title', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='Schedule_Title', max_length=15)),
                ('schedule_content', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='Schedule_Content', max_length=100, null=True)),
                ('start_time', models.DateField(db_column='Start_Time')),
                ('end_time', models.DateField(db_column='End_Time')),
                ('group_code', models.ForeignKey(db_column='Group_Code', on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
            options={
                'db_table': 'group_schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupProject',
            fields=[
                ('project_id', models.IntegerField(db_column='Project_ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='Project_Name', max_length=15)),
                ('project_progress', models.IntegerField(db_column='Project_Progress')),
                ('group_code', models.ForeignKey(db_column='Group_Code', on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
            options={
                'db_table': 'group_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupNotice',
            fields=[
                ('notice_id', models.IntegerField(db_column='Notice_ID', primary_key=True, serialize=False)),
                ('notice_title', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='Notice_Title', max_length=15)),
                ('notice_content', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='Notice_Content', max_length=100, null=True)),
                ('notice_date', models.DateField(db_column='Notice_Date')),
                ('group_code', models.ForeignKey(db_column='Group_Code', on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
            options={
                'db_table': 'group_notice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.ForeignKey(db_column='group_code', on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
                ('member', models.ForeignKey(db_column='Member', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'group_member',
                'managed': True,
            },
        ),
    ]
