# Generated by Django 4.2.1 on 2023-06-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproject',
            name='responsibility',
            field=models.ForeignKey(db_column='Responsiblity', default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
