# Generated by Django 4.2.1 on 2023-06-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groupproject_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotice',
            name='notice_id',
            field=models.CharField(db_column='Notice_ID', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupproject',
            name='project_id',
            field=models.CharField(db_column='Project_ID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
