# Generated by Django 4.2 on 2023-05-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_code', models.IntegerField(db_column='Group_Code', primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='Group_Name', max_length=10)),
                ('creator_id', models.CharField(db_column='Creator_ID', max_length=15)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupNotice',
            fields=[
                ('notice_id', models.IntegerField(db_column='Notice_ID', primary_key=True, serialize=False)),
                ('notice_title', models.CharField(db_column='Notice_Title', max_length=15)),
                ('notice_content', models.CharField(blank=True, db_column='Notice_Content', max_length=100, null=True)),
                ('notice_date', models.DateField(db_column='Notice_Date')),
            ],
            options={
                'db_table': 'group_notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupProject',
            fields=[
                ('project_id', models.IntegerField(db_column='Project_ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='Project_Name', max_length=15)),
                ('project_progress', models.IntegerField(db_column='Project_Progress')),
            ],
            options={
                'db_table': 'group_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('schedule_id', models.IntegerField(db_column='Schedule_ID', primary_key=True, serialize=False)),
                ('schedule_title', models.CharField(db_column='Schedule_Title', max_length=15)),
                ('schedule_content', models.CharField(blank=True, db_column='Schedule_Content', max_length=100, null=True)),
                ('start_time', models.DateField(db_column='Start_Time')),
                ('end_time', models.DateField(db_column='End_Time')),
            ],
            options={
                'db_table': 'group_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTimetable',
            fields=[
                ('timetable_id', models.IntegerField(db_column='Timetable_ID', primary_key=True, serialize=False)),
                ('start_time', models.DateField(db_column='Start_Time')),
                ('end_time', models.DateField(db_column='End_Time')),
            ],
            options={
                'db_table': 'group_timetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.CharField(db_column='Time_ID', max_length=15, primary_key=True, serialize=False)),
                ('day', models.IntegerField(db_column='Day')),
                ('time', models.IntegerField(db_column='Time')),
                ('preference', models.IntegerField(blank=True, db_column='Preference', null=True)),
            ],
            options={
                'db_table': 'time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(db_column='User_ID', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=10)),
                ('email', models.CharField(db_column='Email', max_length=15)),
                ('password', models.CharField(db_column='Password', max_length=20)),
                ('join_date', models.DateField(db_column='Join_Date')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('group_code', models.OneToOneField(db_column='Group_Code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='test_app.group')),
                ('member_id', models.CharField(db_column='Member_ID', max_length=15)),
            ],
            options={
                'db_table': 'group_member',
                'managed': False,
            },
        ),
    ]
